[32mINFO    [0m root:test_004_advanced_features.py:206 **** Starting test_broken_links ****
[1m[31mERROR   [0m root:test_004_advanced_features.py:223 Error checking link https://github.com/tourdedave/the-internet: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /tourdedave/the-internet (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C1A728FB60>: Failed to resolve 'github.com' ([Errno 11001] getaddrinfo failed)"))
[1m[31mERROR   [0m root:test_004_advanced_features.py:223 Error checking link http://elementalselenium.com/: HTTPConnectionPool(host='elementalselenium.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C1A76D8770>, 'Connection to elementalselenium.com timed out. (connect timeout=5)'))
[1m[31mERROR   [0m root:test_004_advanced_features.py:223 Error checking link https://the-internet.herokuapp.com/img/forkme_right_green_007200.png: HTTPSConnectionPool(host='the-internet.herokuapp.com', port=443): Max retries exceeded with url: /img/forkme_right_green_007200.png (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C1A7329590>: Failed to resolve 'the-internet.herokuapp.com' ([Errno 11001] getaddrinfo failed)"))
[1m[31mERROR   [0m root:test_004_advanced_features.py:223 Error checking link https://the-internet.herokuapp.com/asdf.jpg: HTTPSConnectionPool(host='the-internet.herokuapp.com', port=443): Max retries exceeded with url: /asdf.jpg (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C1A7329A90>: Failed to resolve 'the-internet.herokuapp.com' ([Errno 11001] getaddrinfo failed)"))
[1m[31mERROR   [0m root:test_004_advanced_features.py:223 Error checking link https://the-internet.herokuapp.com/hjkl.jpg: HTTPSConnectionPool(host='the-internet.herokuapp.com', port=443): Max retries exceeded with url: /hjkl.jpg (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C1A7329E50>: Failed to resolve 'the-internet.herokuapp.com' ([Errno 11001] getaddrinfo failed)"))
[1m[31mERROR   [0m root:test_004_advanced_features.py:223 Error checking link https://the-internet.herokuapp.com/img/avatar-blank.jpg: HTTPSConnectionPool(host='the-internet.herokuapp.com', port=443): Max retries exceeded with url: /img/avatar-blank.jpg (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C1A732A210>: Failed to resolve 'the-internet.herokuapp.com' ([Errno 11001] getaddrinfo failed)"))
[32mINFO    [0m root:test_004_advanced_features.py:227 **** test_broken_links COMPLETED ****